### ISSUE TITLE
Permit fails when token contract returns unexpected "version"

### ISSUE THREAD

**Issue by dpekar** [vacekj/wagmi-permit#5]
When using `wagmi-permit`, I noticed my permits were failing when interacting with [Balancer](https://balancer.fi/pools/ethereum/v2/0x3de27efa2f1aa663ae5d458857e731c129069f29000200000000000000000588) contracts.  

When I looked in a bit closer, I realized that the `version` function on the [balancer pool contracts](https://etherscan.io/address/0x3de27efa2f1aa663ae5d458857e731c129069f29#readContract#F30) return a json string, obviously used for some other reason:
```{"name":"WeightedPool","version":4,"deployment":"20230320-weighted-pool-v4"}```

The balancer contracts do support permits, but since `wagmi-permit` uses the wrong version, the permits fails.
```
	const { data: versionFromContract } = useContractRead({
		chainId,
		address: contractAddress,
		abi: ERC20ABI,
		functionName: "version",
	});
	const version = permitVersion ?? versionFromContract ?? "1";
```

What about adding some simple validation to `versionFromContract` and using "1" unless `versionFromContract` is an integer?

**Comment by vacekj** [comment]
Hey, thanks for the bug report. I agree with your proposed solution - would you like to submit a PR? Cheers!

**Comment by dpekar** [comment]
Will do when I get a minute in the next week or so!

**Comment by dpekar** [comment]
@vacekj - I don't have write access to push up my branch and submit my PR, but I 
was just thinking something like:

```
const validatedVersionFromContract = [1, 2, '1', '2'].includes(versionFromContract)
    ? versionFromContract
    : null;

const version = permitVersion ?? validatedVersionFromContract ?? '1';
```

How does that look?

Do you wanna open up access or feel free to just use code above if it looks good to you.

**Comment by vacekj** [comment]
@dpekar thanks for the suggestion, that looks good to me. You can fork the repo and submit a PR from your fork

**Comment by dpekar** [comment]
hey @vacekj - do you mind to push an updated version up to npm?

thanks!

**Comment by vacekj** [comment]
Publishing now, thanks!
